### ISSUE TITLE
Unhandled rejection RequestError: Error: write EPROTO

### ISSUE THREAD

**Issue by qianshihua** [gooin/dailysync-rev#1]
# node -v
node版本：v20.15.0

src目录下执行命令：yarn migrate_garmin_cn_to_global
报错如下：
Warn: renew GarminGlobal session..
Unhandled rejection RequestError: Error: write EPROTO 002E5B0A01000000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1590:SSL alert number 40

    at onRequestResponse (/Users/qiansh/Documents/code/DailySync-master/node_modules/cloudscraper/index.js:165:21)
    at Request.<anonymous> (/Users/qiansh/Documents/code/DailySync-master/node_modules/cloudscraper/index.js:144:7)
    at Object.onceWrapper (node:events:634:26)
    at Request.emit (node:events:519:28)
    at Request.emit (node:domain:488:12)
    at Request.onRequestError (/Users/qiansh/Documents/code/DailySync-master/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:519:28)
    at ClientRequest.emit (node:domain:488:12)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

TypeError: Cannot destructure property 'body' of '(intermediate value)' as it is undefined.
    at CFClient.get (/Users/qiansh/Documents/code/DailySync-master/node_modules/@gooin/garmin-connect/dist/common/CFClient.js:92:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GarminConnect.get (/Users/qiansh/Documents/code/DailySync-master/node_modules/@gooin/garmin-connect/dist/garmin/GarminConnect.js:420:26)
    at async GarminConnect.login (/Users/qiansh/Documents/code/DailySync-master/node_modules/@gooin/garmin-connect/dist/garmin/GarminConnect.js:137:33)
    at async getGaminGlobalClient (/Users/qiansh/Documents/code/DailySync-master/src/utils/garmin_global.ts:49:17)
    at async migrateGarminCN2GarminGlobal (/Users/qiansh/Documents/code/DailySync-master/src/utils/garmin_cn.ts:78:26)
::error::TypeError: Cannot destructure property 'body' of '(intermediate value)' as it is undefined.

**Comment by gooin** [comment]
ssh版本太低

**Comment by gooin** [comment]
系统 ssl 版本太低
